# Generated by Django 5.2.12 on 2026-03-22 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('demand_board', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitmentActualSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('committed_qty', models.DecimalField(decimal_places=2, max_digits=12)),
                ('actual_delivered_qty', models.DecimalField(decimal_places=2, max_digits=12)),
                ('variance_qty', models.DecimalField(decimal_places=2, max_digits=12)),
                ('snapshot_date', models.DateField()),
                ('demand_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commitment_snapshots', to='demand_board.demandpost')),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commitment_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'commitment_actual_snapshots',
                'ordering': ['-snapshot_date'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('summary_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'weekly_reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
