# Generated by Django 5.2.12 on 2026-03-22 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_name', models.CharField(max_length=120)),
                ('start_date', models.DateField()),
                ('target_harvest_date', models.DateField()),
                ('area_size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=20)),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_plans', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_plans', to='catalog.product')),
            ],
            options={
                'db_table': 'season_plans',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='SeasonMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone_type', models.CharField(max_length=60)),
                ('due_date', models.DateField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('season_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_milestones', to='season_planner.seasonplan')),
            ],
            options={
                'db_table': 'season_milestones',
                'ordering': ['due_date'],
            },
        ),
    ]
