services:
  - type: web
    name: agriculture-sys-v3-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt && python manage.py migrate && python manage.py seed_demo --reset
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: agriculture-sys-v3-backend.onrender.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://your-frontend.vercel.app