# Generated by Django 5.2.12 on 2026-03-17 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='pod/')),
                ('receiver_name', models.CharField(max_length=120)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('delivered_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=20)),
                ('license_no', models.CharField(max_length=60)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eta', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING_ASSIGNMENT', 'Pending Assignment'), ('SCHEDULED', 'Scheduled'), ('LOADED', 'Loaded'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('DELAYED', 'Delayed'), ('FAILED', 'Failed')], default='PENDING_ASSIGNMENT', max_length=30)),
                ('delay_reason', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('LOADED', 'Loaded'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered')], default='SCHEDULED', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20, unique=True)),
                ('vehicle_type', models.CharField(max_length=60)),
                ('capacity_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
