# Generated by Django 5.2.12 on 2026-03-17 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logistics', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to='orders.order'),
        ),
        migrations.AddField(
            model_name='deliveryproof',
            name='shipment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pod', to='logistics.shipment'),
        ),
    ]
