# Generated by Django 5.2.12 on 2026-03-22 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuidedAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=20)),
                ('action_type', models.CharField(max_length=60)),
                ('title', models.CharField(max_length=120)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('priority', models.PositiveSmallIntegerField(default=50)),
                ('is_done', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guided_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'guided_actions',
                'ordering': ['is_done', '-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReorderAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_level', models.CharField(default='MEDIUM', max_length=20)),
                ('projected_stockout_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ACKNOWLEDGED', 'Acknowledged'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reorder_alerts', to='locations.location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reorder_alerts', to='catalog.product')),
            ],
            options={
                'db_table': 'reorder_alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_qty', models.DecimalField(decimal_places=2, max_digits=12)),
                ('confidence', models.DecimalField(decimal_places=2, max_digits=4)),
                ('reason_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_recommendations', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_recommendations', to='catalog.product')),
            ],
            options={
                'db_table': 'request_recommendations',
                'ordering': ['-created_at'],
            },
        ),
    ]
