# Generated by Django 5.2.12 on 2026-03-22 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0003_v4_workflow_and_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriorityScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('factors_json', models.JSONField(blank=True, default=dict)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='priority_scores', to='orders.order')),
            ],
            options={
                'db_table': 'priority_scores',
                'ordering': ['-calculated_at'],
            },
        ),
    ]
