# Generated by Django 5.2.12 on 2026-03-22 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logistics', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_time_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('proof_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('completion_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('delivery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_score', to='logistics.shipment')),
            ],
            options={
                'db_table': 'delivery_scores',
                'ordering': ['-calculated_at'],
            },
        ),
        migrations.CreateModel(
            name='PodIntegrityFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_type', models.CharField(max_length=40)),
                ('severity', models.CharField(default='MEDIUM', max_length=20)),
                ('reason', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_proof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrity_flags', to='logistics.deliveryproof')),
            ],
            options={
                'db_table': 'pod_integrity_flags',
                'ordering': ['-created_at'],
            },
        ),
    ]
