export const ROLES = {
  ADMIN: 'ADMIN',
  MANAGER: 'MANAGER',
  DISTRIBUTOR: 'DISTRIBUTOR',
}

export const ORDER_STATUSES = [
  'DRAFT',
  'SUBMITTED',
  'UNDER_REVIEW',
  'APPROVED',
  'REJECTED',
  'IN_DELIVERY',
  'DELIVERED',
  'CONFIRMED',
]
