# Generated by Django 5.2.12 on 2026-03-22 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExceptionCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exception_type', models.CharField(max_length=40)),
                ('entity_type', models.CharField(max_length=40)),
                ('entity_id', models.PositiveIntegerField()),
                ('severity', models.CharField(default='MEDIUM', max_length=20)),
                ('owner_role', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ASSIGNED', 'Assigned'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'exceptions',
                'ordering': ['-created_at'],
            },
        ),
    ]
