# Generated by Django 5.2.12 on 2026-03-17 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=120)),
                ('city_municipality', models.CharField(max_length=120)),
                ('barangay', models.CharField(max_length=120)),
                ('postal_code', models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
